### ISSUE TITLE
Create a gulp task for push public files to gh-pages branch

### ISSUE THREAD

**Issue by diogomoretti** [FloripaJS/klipim#1]
- [x] Create gulp task for push public files to `gh-pages` branch
- [x] Create a file called `CNAME` with `klip.im` domain

**Comment by fdaciuk** [comment]
@diogomoretti is `klip.im` domain ready to show this repository? Did you set Github's DNS entries?

**Comment by diogomoretti** [comment]
Not yet @fdaciuk... I will do right now!

**Comment by diogomoretti** [comment]
Done @fdaciuk!

**Comment by fdaciuk** [comment]
Very nice! :dancer:

**Comment by fdaciuk** [comment]
@diogomoretti Done! http://klip.im is online :dancers: :sparkles:

**Comment by diogomoretti** [comment]
Great @fdaciuk =] IS AWESOME!
