### ISSUE TITLE
Pode publicar o site ao menos em http://floripajs.github.io/klipim/ ?

### ISSUE THREAD

**Issue by fititnt** [floripajs/klipim#13]
Domínio http://klip.im/ está fora do ar. Pode publicar o site ao menos em http://floripajs.github.io/klipim/ ?

**Comment by diogomoretti** [comment]
Fala @fititnt, vou arrumar isso. Quando fizer, ai eu fecho a issue. Valeu por avisar.

**Comment by fititnt** [comment]
Estou vendo que foi feito, mas você tinha esquecido de fechar. Ta resolvido esse.
