### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by fmoliveira** [floripajs/klipim#9]
Hello,

The project is awesome and I'm willing to contribute by adding new stickers and to the source code as well.

Perhaps the @floripajs staff could write some contributing guidelines?

I've got a doubt that could have been answered easily with contributing guidelines, please [check here](https://github.com/floripajs/klipim/issues/8).

**Comment by diogomoretti** [comment]
The project does not have readme and contributing (.md`s), you can help us create both.

**Comment by fmoliveira** [comment]
Fine, I'll get it started then!

**Comment by fmoliveira** [comment]
I'll make atomic pull requests because I think it'll be better for us to discuss about possible changes.

A basic README.md is being added at #11 . A new pull request will come with a CONTRIBUTING.md file.
